lobby:
  world: world
  x: 55.5
  y: -52
  z: 30.5
  yaw: 0
  pitch: 0
specialBlocks:
maps:
  test:
    attackerspawn:
      world: world
      x: 24.5
      y: -59
      z: 57.5
      yaw: 0
      pitch: 0
    attackervillager:
      world: world
      x: 21.5
      y: -59
      z: 57.5
      yaw: -90
      pitch: 0
    defenderspawn:
      world: world
      x: 24.5
      y: -59
      z: 83.5
      yaw: -90
      pitch: 0
    defendervillager:
      world: world
      x: 21.5
      y: -59
      z: 83.5
      yaw: -90
      pitch: 0
    creeper:
        world: world
        x: 24.5
        y: -59
        z: 70.5
        yaw: -90
        pitch: 0