name: CreeperCataclysm
version: '${project.version}'
main: com.skle.creepercataclysm.CreeperCataclysm
api-version: 1.20
commands:
  play:
    description: Queue up for a game
    usage: /<command>
    aliases: [join, p, j]
  queue:
    description: List the players in queue
    usage: /<command>
    aliases: [q]
  leave:
    description: Leave the queue for a game
    usage: /<command>
    aliases: [l, quit, q]