name: CreeperCataclysm
version: '${project.version}'
main: com.skle.creepercataclysm.CreeperCataclysm
api-version: 1.20
depend: [ ProtocolLib ]
load: POSTWORLD
commands:
  play:
    description: Queue up for a game
    usage: /<command> <player>
    aliases: [join, p, j]
  queue:
    description: List the players in queue
    usage: /<command>
    aliases: [q]
  leave:
    description: Leave the queue for a game
    usage: /<command>
    aliases: [l, quit, q]
  setplayers:
    description: Set the number of players in a game
    usage: /<command> <number>
    aliases: []
  settime:
    description: Set the time for a game
    usage: /<command> <number>
    aliases: [st]
  abort:
    description: Abort the game
    usage: /<command>
    aliases: [a]
  tpsnow:
    description: Teleport to the snow
    usage: /<command>
    aliases: []
  forcestart:
    description: Force start the game
    usage: /<command>
    aliases: [fs, start]
  addgold:
    description: Add gold to a player
    usage: /<command> <player> <amount>
    aliases: [ag]
  zonelobby:
    description: Set the lobby zone
    usage: /<command>
    aliases: []
  zonemap:
    description: Set the map zone
    usage: /<command> <map>
    aliases: []
  reloadconfig:
    description: Reload the config
    usage: /<command>
    aliases: []
  cancelzone:
    description: Cancel the zone selection
    usage: /<command>
    aliases: []
  setSpecial:
    description: Set the block to healing item
    usage: /<command>
    aliases: []
  creepercommands:
    description: List all the commands
    usage: /<command>
    aliases: [cc, helpcreeper]
  switchteam:
    description: Switch teams
    usage: /<command>
    aliases: [st]
  resetdeaths:
    description: Reset the deaths of all players
    usage: /<command>
    aliases: [rd]

